services:
  - type: web
    name: hospital-management-system
    env: python
    buildCommand: |
      chmod +x build.sh
      ./build.sh
    startCommand: gunicorn app:app --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        generateValue: true
      - key: MFA_ENCRYPTION_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: FLASK_APP
        value: app.py
      - key: RENDER
        value: true
      - key: DATABASE_URL
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_ENDPOINT_URL
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
    healthCheckPath: /ready
    autoDeploy: true
    plan: free
